### ISSUE TITLE
"Send your certificate" feature does not work for me

### ISSUE THREAD

**Issue by khunshwephyo** [OpenCerts/opencerts-website#318] opened 2019-06-06 09:05 UTC
Students reported that they cannot send email using "Send your certificate" feature.  When I tried at development site, it also fails with an error message.

![image](https://user-images.githubusercontent.com/25623914/59020711-208e5880-887d-11e9-939b-e20e71ba4ec9.png)

Chrome dev tools show this error.

![image](https://user-images.githubusercontent.com/25623914/59020762-3ac83680-887d-11e9-904b-dd461a7a5522.png)

**Comment by yehjxraymond** [comment] 2019-06-06 09:08
Hi,

We are in the midst of migrating existing resources from a host to another. That API is currently down until our SES is moved out of the sandbox. 

So utterly sorry for the inconvenience. We will let you know via this issue when it has been resolve. Seek your patience here. Thank you.

**Comment by khunshwephyo** [comment] 2019-06-06 09:24
No worries.  Thank you for the quick response.

**Comment by yehjxraymond** [comment] 2019-06-10 01:38
Hi Phyo, 

The issue is now fixed. Thank you for your patience. Do let me know if it’s still not working for you.

Will close this issue now.

**Closed by yehjxraymond** 2019-06-10 01:38 UTC

**Comment by khunshwephyo** [comment] 2019-06-13 09:00
Students are now able to  send email.  Thanks!
