### ISSUE TITLE
Integration Test error 

### ISSUE THREAD

**Issue by RP-OIS-SK** [OpenCerts/opencerts-website#148] opened 2019-04-08 01:37 UTC
Getting inconsistent result the integration test.  For the same script, sometime I get successful test result and sometime getting error running integration test.  

The following is the log 

> opencerts-website@2.0.0 integration D:\opencerts-website
> testcafe chrome src/**/*.spec.js

 Running tests in:
 - Chrome 73.0.3683 / Windows 10.0.0

 Default Certificate Template
 × Default certificate is rendered correctly

   1) A JavaScript error occurred on "http://localhost:3000/".
      At this moment, TestCafe tracks uncaught JavaScript errors on the page. Try to manually perform the test
      scenario.
      If this error still occurs then it means you site has uncaught JavaScript errors. To disable JavaScript error
      tracking you can turn the --skip-js-errors option on.
      If the error occurs only with TestCafe then it is a bug. Write a new issue about it at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      TypeError: Cannot read property 'fn' of undefined
          at https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js:7:2805
          at https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js:7:2997
          at https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js:7:200
          at https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js:7:236

      Browser: Chrome 73.0.3683 / Windows 10.0.0

         14 |const BannerPrivacyFilter = Selector("#banner-privacy-filter");
         15 |const RenderedCertificate = Selector("#rendered-certificate");
         16 |
         17 |test("Default certificate is rendered correctly", async t => {
         18 |  // Uploads certificate via dropzone
       > 19 |  await t.setFilesToUpload("input[type=file]", [Certificate]);
         20 |  await t.click(ButtonViewCertificateAnyway);
         21 |
         22 |  // Validates rendering of the certificate
         23 |  // Header items rendered
         24 |  await t

         at setFilesToUpload
      (D:\opencerts-website\src\components\CertificateTemplates\Default\integration.spec.js:19:11)
         at step (D:\opencerts-website\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
         at <anonymous> (D:\opencerts-website\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14)
         at new F (D:\opencerts-website\node_modules\core-js\library\modules\_export.js:36:28)
         at <anonymous> (D:\opencerts-website\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12)
         at test (D:\opencerts-website\src\components\CertificateTemplates\Default\integration.spec.js:17:1)
         at markeredfn (D:\opencerts-website\node_modules\testcafe\src\api\wrap-test-function.js:17:28)
         at step (D:\opencerts-website\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
         at <anonymous> (D:\opencerts-website\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14)
         at new F (D:\opencerts-website\node_modules\core-js\library\modules\_export.js:36:28)

 Republic Polytechnic
 × PET certificate is rendered correctly

   1) A JavaScript error occurred on "http://localhost:3000/".
      At this moment, TestCafe tracks uncaught JavaScript errors on the page. Try to manually perform the test
      scenario.
      If this error still occurs then it means you site has uncaught JavaScript errors. To disable JavaScript error
      tracking you can turn the --skip-js-errors option on.
      If the error occurs only with TestCafe then it is a bug. Write a new issue about it at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      TypeError: Cannot read property 'fn' of undefined
          at https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js:7:2805
          at https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js:7:2997
          at https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js:7:200
          at https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js:7:236

      Browser: Chrome 73.0.3683 / Windows 10.0.0

         13 |    Promise.resolve()
         14 |  );
         15 |
         16 |test("PET certificate is rendered correctly", async t => {
         17 |  // Uploads certificate via dropzone
       > 18 |  await t.setFilesToUpload("input[type=file]", [Certificate]);
         19 |
         20 |  // Certificate tabs rendered
         21 |  await t.expect(TemplateTabList.textContent).contains("Certificate");
         22 |  await t.expect(TemplateTabList.textContent).contains("Transcript");
         23 |

         at setFilesToUpload
      (D:\opencerts-website\src\components\CertificateTemplates\tlds\sg\edu\rp\2018-P-MAIN\integration.spec.js:18:11)
         at step (D:\opencerts-website\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
         at <anonymous> (D:\opencerts-website\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14)
         at new F (D:\opencerts-website\node_modules\core-js\library\modules\_export.js:36:28)
         at <anonymous> (D:\opencerts-website\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12)
         at test
      (D:\opencerts-website\src\components\CertificateTemplates\tlds\sg\edu\rp\2018-P-MAIN\integration.spec.js:16:1)
         at markeredfn (D:\opencerts-website\node_modules\testcafe\src\api\wrap-test-function.js:17:28)
         at step (D:\opencerts-website\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
         at <anonymous> (D:\opencerts-website\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14)
         at new F (D:\opencerts-website\node_modules\core-js\library\modules\_export.js:36:28)

**Comment by yehjxraymond** [comment] 2019-04-09 05:25
May I know if you were using the command `npm run integration` with `npm run dev`? 

If that is the case, could you try `npm run integration` with `npm run start`. 

I'm suspecting it is something to do with the development build, `npm run start` will deploy the production build for integration test to run.

Also, it will help if you can tell us which branch/PR your are running the test on. Console errors on that branch may fail the integration test.

**Comment by RP-OIS-SK** [comment] 2019-04-10 04:37
Hi Raymond,

Yes.  I am using npm run dev. I still getting the same error using npm run
start.

Is it related to other code issue ? Saw some issue raised.

Thanks

SK.

**Comment by rjchow** [comment] 2019-04-10 04:40
I tried running integration tests 20 times on your repo/branch yesterday
using windows but I didn't get an error - is that the code you're running
the test on? or do you have uncommitted code

**Comment by RP-OIS-SK** [comment] 2019-04-10 09:38
Hi Raymond,

There is no uncommitted code.  I get some error for pull request also.

SK

**Comment by rjchow** [comment] 2019-04-12 07:27
I'm not really sure how to troubleshoot this because we can't reproduce it on any of our environments

**Comment by yehjxraymond** [comment] 2019-04-16 09:21
Please see comment on PR. Closing issue.

**Closed by yehjxraymond** 2019-04-16 09:21 UTC
